### ISSUE TITLE
TO-DO List v2.0.0

### ISSUE THREAD

**Issue by daniel022302** [SpecterTeam/UHC#2]
# **Suggestions for these project: v2.0.0**
## Scenarios to be added:
- [ ] BareBones
- [ ] Backpack
- [ ] BloodDiamonds
- [x] CutClean
- [ ] Death Kick/Spectate
- [ ] Diamondless
- [ ] Fireless
- [ ] Goldless
- [x] GoldenHead
- [ ] NoCleanUp
- [x] NoEnchant *Lol there is already no enchants on pmmp*
- [x] NoFall
- [ ] NoBuckets
- [ ] NoW10
- [ ] SpiderBow
- [x] StatueonDeath
- [x] TimeBomb

### - /team:
- [ ] add
- [ ] remove
- [ ] set [0-10]
- [ ] attack [on/off]

### - /host:
- [ ] Sent a UI with host commands

### - /border:
- [ ] use [shrink,time-tp]
- [ ] shrink [value]
- [ ] size [value]
- [ ] type [bedrock,kb]

**Comment by pranavbhuv** [comment]
wow, very descriptive

**Comment by daniel022302** [comment]
Fris knows all of these since he used to own a uhc server. Ill add Description to it later

**Comment by OGFris** [comment]
Quiverly' meant it when he said you are very descriptive and yeah i will add them soon :)

**Comment by daniel022302** [comment]
Ohhh lol

**Comment by pranavbhuv** [comment]
What do any of these do?

**Comment by Infernus101** [comment]
Exactly my question lol

**Comment by daniel022302** [comment]
I'll make a brief description soon

**Comment by OGFris** [comment]
i already know what they do but your help is welcome @daniel022302  :)

**Comment by daniel022302** [comment]
NP, I think you know me, huge fan of your success, my Twitter is GamerVideosHD

**Comment by OGFris** [comment]
oh yeah, thanks <3

**Comment by shavindanagapen** [comment]
Is this plugin done?

**Comment by OGFris** [comment]
Not yet @CyanCreeperPlayz

**Comment by ghost** [comment]
This UHC plugin is going to be lit. Just Like PC Badlion

**Comment by OGFris** [comment]
thank you for the support :+1:

**Comment by RushEnte** [comment]
Pls start

**Comment by janleigh** [comment]
Pls revive the project
